/* Generated by Retr01 Studio export. */
#ifndef R01_GAME_H
#define R01_GAME_H

#include <stdint.h>

typedef struct R01GameCtx {
    int player_x;
    int player_y;
    int cam_x;
    int cam_y;
    uint8_t pad;
    uint8_t pad_prev;
    int cam_deadzone_x;
    int cam_deadzone_y;
    int cam_axis_lock;
    int bg0_wrap_x;
    int bg0_wrap_y;
    int bg0_clip_bg1;
    int fade_level;
    int fade_target;
    int fade_color;
    int fade_pending_entrance;
    int player_anim_state;
    int player_anim_frame;
    int player_anim_ctr;
    int player_anim_flip_h;
    int player_anim_dir;
    int player_anim_moving;
    int player_default_face;
    int player_idle_state;
    int player_walk_state[8];
    int player_state_delay[4];
    int player_crouch_state;
    int player_crouching;
    int player_jump_state;
    int player_airborne;
    int game_mode;
    int plat_gravity;
    int plat_jump;
    int plat_meter;
    int plat_vel_y;
    int plat_frac_x;
    int plat_frac_y;
    int plat_grounded;
    int plat_jump_held;
    int player_run_on_x;
    int bgm_track;
    struct R01Projectile {
        int active;
        int x, y, vx, vy, ttl;
        uint8_t tile, pal;
    } projectiles[8];
} R01GameCtx;

void r01_game_init(R01GameCtx *ctx);
void r01_game_tick(R01GameCtx *ctx);
void r01_game_vblank(R01GameCtx *ctx);

void r01_custom_on_init(R01GameCtx *ctx);
void r01_custom_on_tick(R01GameCtx *ctx);
void r01_custom_on_vblank(R01GameCtx *ctx);

#endif
