/* AUTO-GENERATED by Retr01 Studio export. Do not edit. */
#include "include/r01_game.h"
#include "include/r01_engine.h"

typedef struct {
    int type_id;
    int world_x;
    int world_y;
} R01InstRec;

static const uint8_t play_present[8] = {0, 0, 0, 24, 24, 0, 0, 0};
static const uint8_t play_spawn_col = 3;
static const uint8_t play_spawn_row = 3;
static const int player_entity = 0;
static const R01InstRec entity_insts[1] = {
    {0, 444, 444}
};
static const int entity_inst_count = 1;
static const int player_inst_x = 444;
static const int player_inst_y = 444;
static const int player_hit_x = 3;
static const int player_hit_y = 8;
static const int player_hit_w = 8;
static const int player_hit_h = 8;
const int player_state_frames[4] = {1, 3, 1, 1};

typedef struct { const char *id; int sc, sr, tc, tr; } R01WarpEntRec;
typedef struct { int ent; int dsc, dsr, dtc, dtr; uint8_t flags; } R01WarpExitRec;
static const R01WarpEntRec warp_ents[1] = {{0}};
static const R01WarpExitRec warp_exits[1] = {{0}};
static const int warp_ent_count = 0;
static const int warp_exit_count = 0;

static int player_instance_spawn(int *out_x, int *out_y) {
    int i;
    if (player_entity < 0) return 0;
    for (i = 0; i < entity_inst_count; i++) {
        if (entity_insts[i].type_id != player_entity) continue;
        if (out_x) *out_x = entity_insts[i].world_x;
        if (out_y) *out_y = entity_insts[i].world_y;
        return 1;
    }
    return 0;
}

void r01_game_init(R01GameCtx *ctx) {
    int sx, sy;
    (void)play_present;
    (void)player_hit_x; (void)player_hit_y;
    (void)player_hit_w; (void)player_hit_h;
    if (!ctx) return;
    r01_game_ctx_init(ctx);
    if (!player_instance_spawn(&sx, &sy)) {
        sx = play_spawn_col * 128 + (128 - 8) / 2;
        sy = play_spawn_row * 120 + (120 - 8) / 2;
    }
    ctx->player_x = sx;
    ctx->player_y = sy;
    r01_custom_on_init(ctx);
    r01_game_camera_snap(ctx);
}

void r01_game_tick(R01GameCtx *ctx) {
    if (!ctx) return;
    if (r01_pad_just_pressed(ctx, R01_BTN_X)) {
        r01_player_warp(ctx, 0, 0);
    }
    if (r01_pad_just_pressed(ctx, R01_BTN_Y)) {
        r01_player_warp(ctx, 1, 0);
    }
    r01_runtime_dispatch_buttons(ctx);
    ctx->pad_prev = ctx->pad;
    r01_custom_on_tick(ctx);
}

void r01_game_vblank(R01GameCtx *ctx) {
    if (!ctx) return;
    r01_custom_on_vblank(ctx);
}
