/* Generated by Retr01 Studio export. */
#ifndef R01_GAME_H
#define R01_GAME_H

#include <stdint.h>

typedef struct R01GameCtx {
    int player_x;
    int player_y;
    int cam_x;
    int cam_y;
    uint8_t pad;
    uint8_t pad_prev;
} R01GameCtx;

void r01_game_init(R01GameCtx *ctx);
void r01_game_tick(R01GameCtx *ctx);
void r01_game_vblank(R01GameCtx *ctx);

void r01_custom_on_init(R01GameCtx *ctx);
void r01_custom_on_tick(R01GameCtx *ctx);
void r01_custom_on_vblank(R01GameCtx *ctx);

#endif
