from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

generate = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'SST39SF040', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SST39SF040'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DIP:DIP-32_W15.24mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC),
            Pin(num='3',name='3',func=pin_types.UNSPEC),
            Pin(num='4',name='4',func=pin_types.UNSPEC),
            Pin(num='5',name='5',func=pin_types.UNSPEC),
            Pin(num='6',name='6',func=pin_types.UNSPEC),
            Pin(num='7',name='7',func=pin_types.UNSPEC),
            Pin(num='8',name='8',func=pin_types.UNSPEC),
            Pin(num='9',name='9',func=pin_types.UNSPEC),
            Pin(num='10',name='10',func=pin_types.UNSPEC),
            Pin(num='11',name='11',func=pin_types.UNSPEC),
            Pin(num='12',name='12',func=pin_types.UNSPEC),
            Pin(num='13',name='13',func=pin_types.UNSPEC),
            Pin(num='14',name='14',func=pin_types.UNSPEC),
            Pin(num='15',name='15',func=pin_types.UNSPEC),
            Pin(num='16',name='16',func=pin_types.UNSPEC),
            Pin(num='17',name='17',func=pin_types.UNSPEC),
            Pin(num='18',name='18',func=pin_types.UNSPEC),
            Pin(num='19',name='19',func=pin_types.UNSPEC),
            Pin(num='20',name='20',func=pin_types.UNSPEC),
            Pin(num='21',name='21',func=pin_types.UNSPEC),
            Pin(num='22',name='22',func=pin_types.UNSPEC),
            Pin(num='23',name='23',func=pin_types.UNSPEC),
            Pin(num='24',name='24',func=pin_types.UNSPEC),
            Pin(num='25',name='25',func=pin_types.UNSPEC),
            Pin(num='26',name='26',func=pin_types.UNSPEC),
            Pin(num='27',name='27',func=pin_types.UNSPEC),
            Pin(num='28',name='28',func=pin_types.UNSPEC),
            Pin(num='29',name='29',func=pin_types.UNSPEC),
            Pin(num='30',name='30',func=pin_types.UNSPEC),
            Pin(num='31',name='31',func=pin_types.UNSPEC),
            Pin(num='32',name='32',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'24C64', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'24C64'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DIP:DIP-8_W7.62mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC),
            Pin(num='3',name='3',func=pin_types.UNSPEC),
            Pin(num='4',name='4',func=pin_types.UNSPEC),
            Pin(num='5',name='5',func=pin_types.UNSPEC),
            Pin(num='6',name='6',func=pin_types.UNSPEC),
            Pin(num='7',name='7',func=pin_types.UNSPEC),
            Pin(num='8',name='8',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'CART_EDGE_36', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CART_EDGE_36'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Retr01_Lib:Cart_Edge_2x18_P2.54mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC),
            Pin(num='3',name='3',func=pin_types.UNSPEC),
            Pin(num='4',name='4',func=pin_types.UNSPEC),
            Pin(num='5',name='5',func=pin_types.UNSPEC),
            Pin(num='6',name='6',func=pin_types.UNSPEC),
            Pin(num='7',name='7',func=pin_types.UNSPEC),
            Pin(num='8',name='8',func=pin_types.UNSPEC),
            Pin(num='9',name='9',func=pin_types.UNSPEC),
            Pin(num='10',name='10',func=pin_types.UNSPEC),
            Pin(num='11',name='11',func=pin_types.UNSPEC),
            Pin(num='12',name='12',func=pin_types.UNSPEC),
            Pin(num='13',name='13',func=pin_types.UNSPEC),
            Pin(num='14',name='14',func=pin_types.UNSPEC),
            Pin(num='15',name='15',func=pin_types.UNSPEC),
            Pin(num='16',name='16',func=pin_types.UNSPEC),
            Pin(num='17',name='17',func=pin_types.UNSPEC),
            Pin(num='18',name='18',func=pin_types.UNSPEC),
            Pin(num='19',name='19',func=pin_types.UNSPEC),
            Pin(num='20',name='20',func=pin_types.UNSPEC),
            Pin(num='21',name='21',func=pin_types.UNSPEC),
            Pin(num='22',name='22',func=pin_types.UNSPEC),
            Pin(num='23',name='23',func=pin_types.UNSPEC),
            Pin(num='24',name='24',func=pin_types.UNSPEC),
            Pin(num='25',name='25',func=pin_types.UNSPEC),
            Pin(num='26',name='26',func=pin_types.UNSPEC),
            Pin(num='27',name='27',func=pin_types.UNSPEC),
            Pin(num='28',name='28',func=pin_types.UNSPEC),
            Pin(num='29',name='29',func=pin_types.UNSPEC),
            Pin(num='30',name='30',func=pin_types.UNSPEC),
            Pin(num='31',name='31',func=pin_types.UNSPEC),
            Pin(num='32',name='32',func=pin_types.UNSPEC),
            Pin(num='33',name='33',func=pin_types.UNSPEC),
            Pin(num='34',name='34',func=pin_types.UNSPEC),
            Pin(num='35',name='35',func=pin_types.UNSPEC),
            Pin(num='36',name='36',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'C_100N', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C_100N'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_THT:C_Disc_D5.0mm_W2.5mm_P5.00mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'R_0', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R_0'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] })])