#ifndef R01_ENTITY_IDS_H
#define R01_ENTITY_IDS_H

/* Generated by Studio export. Overwrite OK. */

#define R01_ENT_TYPE_MAX 32
#define R01_ENT_TYPE_COUNT 2
#define R01_ENT_MARKED_PLAYER 0
#define R01_ENT_PLAYER 0
#define R01_ENT_SLIME 1

#endif
