#include "retr01_studio/cart.h"

#include "retr01_studio/chr_pack.h"
#include "retr01_studio/palette.h"
#include "retr01_studio/spr_pack.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define HDR_SIZE 16
#define PTR_TABLE_SIZE 24
#define WORLD_SLOT_SIZE 8
#define WORLD_TABLE_SIZE (R01_MAX_WORLDS * WORLD_SLOT_SIZE)
#define WORLD_HDR_SIZE 32
#define SCREEN_DIR_ENT 12
#define PLANE_DIR_ENT 8
#define SCREEN_PAYLOAD 480

typedef struct Buf {
    uint8_t *data;
    size_t len;
    size_t cap;
} Buf;

static void set_err(char *err_buf, size_t err_cap, const char *msg) {
    if (err_buf && err_cap > 0) {
        snprintf(err_buf, err_cap, "%s", msg ? msg : "error");
    }
}

static int buf_reserve(Buf *b, size_t need) {
    uint8_t *n;
    size_t cap;
    if (need <= b->cap) {
        return 0;
    }
    cap = b->cap ? b->cap : 4096;
    while (cap < need) {
        cap *= 2;
    }
    n = (uint8_t *)realloc(b->data, cap);
    if (!n) {
        return -1;
    }
    b->data = n;
    b->cap = cap;
    return 0;
}

static int buf_append(Buf *b, const void *src, size_t n) {
    if (buf_reserve(b, b->len + n) != 0) {
        return -1;
    }
    memcpy(b->data + b->len, src, n);
    b->len += n;
    return 0;
}

static int buf_pad(Buf *b, size_t to_len, uint8_t fill) {
    if (to_len < b->len) {
        return -1;
    }
    if (buf_reserve(b, to_len) != 0) {
        return -1;
    }
    memset(b->data + b->len, fill, to_len - b->len);
    b->len = to_len;
    return 0;
}

static void put_u8(uint8_t *p, uint8_t v) {
    p[0] = v;
}

static void put_u24(uint8_t *p, uint32_t v) {
    p[0] = (uint8_t)(v & 0xFFu);
    p[1] = (uint8_t)((v >> 8) & 0xFFu);
    p[2] = (uint8_t)((v >> 16) & 0xFFu);
}

static uint32_t get_u24(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16);
}

void r01_prom_fill(uint8_t out64[R01_MASTER_COLORS]) {
    int i;
    for (i = 0; i < R01_MASTER_COLORS; i++) {
        uint8_t r, g, b;
        r01_kit_rgb(i, &r, &g, &b);
        out64[i] = r01_quantize_r3g3b2(r, g, b);
    }
}

int r01_prom_write(const char *path, char *err_buf, size_t err_cap) {
    uint8_t prom[R01_MASTER_COLORS];
    FILE *f;
    if (!path) {
        set_err(err_buf, err_cap, "bad args");
        return -1;
    }
    r01_prom_fill(prom);
    f = fopen(path, "wb");
    if (!f) {
        set_err(err_buf, err_cap, "cannot write prom");
        return -1;
    }
    if (fwrite(prom, 1, sizeof(prom), f) != sizeof(prom)) {
        fclose(f);
        set_err(err_buf, err_cap, "prom write failed");
        return -1;
    }
    fclose(f);
    return 0;
}

void r01_prg_fill_stub(uint8_t prg[R01_PRG_BYTES], const R01Project *p) {
    static const uint8_t code[] = {
        0x78,             /* sei */
        0xD8,             /* cld */
        0xA2, 0xFF,       /* ldx #$ff */
        0x9A,             /* txs */
        0xA9, 0x00,       /* lda #START_WORLD (always 0; no cart header field yet) */
        0x8D, 0x30, 0xFE, /* sta $FE30 */
        0xA9, 0x00,       /* lda #0 */
        0x8D, 0x02, 0xFE, /* sta $FE02 */
        0x8D, 0x03, 0xFE, /* sta $FE03 */
        0x4C, 0x00, 0x80, /* jmp hang (patched) */
    };
    uint16_t hang;
    memset(prg, 0xEA, R01_PRG_BYTES);
    memcpy(prg, code, sizeof(code));
    if (p) {
        /* Boot world is fixed at 0 — active_world is an editor UI tab, not a cart field. */
        prg[6] = 0;
        prg[0x0100] = (uint8_t)p->constraints.scroll_mode;
        prg[0x0101] = (uint8_t)p->constraints.transition;
        prg[0x0102] = (uint8_t)(p->has_cart_save ? 1 : 0);
    }
    hang = 0x8000u + (uint16_t)(sizeof(code) - 3);
    {
        size_t j = sizeof(code) - 3;
        prg[j] = 0x4C;
        prg[j + 1] = (uint8_t)(hang & 0xFF);
        prg[j + 2] = (uint8_t)((hang >> 8) & 0xFF);
    }
    memset(prg + 0x7E00, 0x00, 0x100);
    prg[0x7FFA] = (uint8_t)(hang & 0xFF);
    prg[0x7FFB] = (uint8_t)((hang >> 8) & 0xFF);
    prg[0x7FFC] = 0x00;
    prg[0x7FFD] = 0x80;
    prg[0x7FFE] = (uint8_t)(hang & 0xFF);
    prg[0x7FFF] = (uint8_t)((hang >> 8) & 0xFF);
}

int r01_prg_write_asm(const R01Project *p, const char *path, char *err_buf, size_t err_cap) {
    FILE *f;
    const R01Constraints *c;
    if (!p || !path) {
        set_err(err_buf, err_cap, "bad args");
        return -1;
    }
    c = &p->constraints;
    f = fopen(path, "wb");
    if (!f) {
        set_err(err_buf, err_cap, "cannot write asm");
        return -1;
    }
    fprintf(f, "; Retr01 boot stub — generated by Studio Phase 5\n");
    fprintf(f, "; Assemble with ca65; Studio embeds an equivalent binary stub.\n");
    fprintf(f, ".setcpu \"65C02\"\n\n");
    fprintf(f, "SCROLL_PIXEL    = %d\n", R01_SCROLL_PIXEL);
    fprintf(f, "SCROLL_DEADZONE = %d\n", R01_SCROLL_DEADZONE);
    fprintf(f, "SCROLL_INSTANT  = %d\n", R01_SCROLL_INSTANT);
    fprintf(f, "SCROLL_HYBRID   = %d\n", R01_SCROLL_HYBRID);
    fprintf(f, "XITION_CUT      = %d\n", R01_XITION_CUT);
    fprintf(f, "XITION_FADE     = %d\n\n", R01_XITION_FADE);
    fprintf(f, "C_PLAYER_META     = %d\n", c->player_meta);
    fprintf(f, "C_ENEMY_ANIM_RATE = %d\n", c->enemy_anim_rate);
    fprintf(f, "C_ANIM_RATE       = %d\n", c->anim_rate);
    fprintf(f, "C_SCROLL_MODE     = %d\n", c->scroll_mode);
    fprintf(f, "C_DEADZONE_X      = %d\n", c->deadzone_x);
    fprintf(f, "C_DEADZONE_Y      = %d\n", c->deadzone_y);
    fprintf(f, "C_TRANSITION      = %d\n", c->transition);
    fprintf(f, "CART_HAS_I2C_SAVE = %d\n", p->has_cart_save ? 1 : 0);
    fprintf(f, "START_WORLD       = 0\n\n"); /* fixed until a cart header start-world field exists */
    fprintf(f, "SCROLL_X  = $FE02\n");
    fprintf(f, "SCROLL_Y  = $FE03\n");
    fprintf(f, "WORLD     = $FE30\n\n");
    fprintf(f, ".segment \"CODE\"\n.org $8000\n");
    fprintf(f, "reset:\n");
    fprintf(f, "        sei\n        cld\n        ldx #$ff\n        txs\n");
    fprintf(f, "        lda #START_WORLD\n        sta WORLD\n");
    fprintf(f, "        lda #0\n        sta SCROLL_X\n        sta SCROLL_Y\n");
    fprintf(f, "hang:\n        jmp hang\n\n");
    fprintf(f, ".segment \"VECTORS\"\n.org $FFFA\n");
    fprintf(f, "        .word hang\n        .word reset\n        .word hang\n");
    fclose(f);
    return 0;
}

static void prepare_world_chr(R01World *w) {
    int b;
    for (b = 0; b < R01_BG_BANKS; b++) {
        (void)r01_chr_pack_world_bank(w, b);
    }
    for (b = 0; b < R01_SPR_BANKS; b++) {
        (void)r01_spr_pack_world_bank(w, b);
    }
}

static int append_pal_rows(Buf *b, const R01PalRow rows[R01_PAL_ROWS]) {
    int i, c;
    uint8_t tmp[R01_PAL_ROWS * R01_PAL_COLORS];
    for (i = 0; i < R01_PAL_ROWS; i++) {
        for (c = 0; c < R01_PAL_COLORS; c++) {
            tmp[i * R01_PAL_COLORS + c] = rows[i].idx[c] & 63u;
        }
    }
    return buf_append(b, tmp, sizeof(tmp));
}

static int build_world_blob(Buf *blob, const R01World *w) {
    uint8_t hdr[WORLD_HDR_SIZE];
    uint8_t dir[R01_MAX_SCREENS_PER_WORLD * SCREEN_DIR_ENT];
    uint8_t pdir[R01_MAX_PARALLAX_PLANES * PLANE_DIR_ENT];
    size_t off_chr, off_sdir, off_pdir, off_spay, off_wpal_bg, off_wpal_spr;
    int si, pi, bi;
    int start_col = 0, start_row = 0;
    int parallax_count = 0;
    uint32_t payload_base;

    memset(hdr, 0, sizeof(hdr));
    memset(dir, 0, sizeof(dir));
    memset(pdir, 0, sizeof(pdir));

    if (w->screen_count > 0 && w->screens[0].present) {
        start_col = w->screens[0].col;
        start_row = w->screens[0].row;
    }
    for (pi = 0; pi < R01_MAX_PARALLAX_PLANES; pi++) {
        if (w->planes[pi].present) {
            parallax_count++;
        }
    }

    off_chr = WORLD_HDR_SIZE;
    off_wpal_bg = 0;
    off_wpal_spr = 0;
    {
        size_t cursor = off_chr + (size_t)R01_BG_BANKS * R01_CHR_BANK_BYTES +
                        (size_t)R01_SPR_BANKS * R01_CHR_BANK_BYTES;
        if (w->use_world_pals) {
            off_wpal_bg = cursor;
            cursor += 16;
            off_wpal_spr = cursor;
            cursor += 16;
        }
        off_sdir = cursor;
        cursor += (size_t)w->screen_count * SCREEN_DIR_ENT;
        off_pdir = cursor;
        cursor += (size_t)parallax_count * PLANE_DIR_ENT;
        off_spay = cursor;
        payload_base = (uint32_t)off_spay;
    }

    put_u8(hdr + 0, (uint8_t)start_col);
    put_u8(hdr + 1, (uint8_t)start_row);
    put_u8(hdr + 2, (uint8_t)(w->default_bg_bank & 3));
    put_u8(hdr + 3, 0);
    put_u8(hdr + 4, (uint8_t)(w->default_pal_row & 3));
    put_u8(hdr + 5, (uint8_t)w->screen_count);
    put_u8(hdr + 6, (uint8_t)parallax_count);
    put_u8(hdr + 7, 0);
    put_u24(hdr + 8, (uint32_t)off_chr);
    put_u24(hdr + 11, (uint32_t)off_sdir);
    put_u24(hdr + 14, (uint32_t)off_pdir);
    put_u24(hdr + 17, (uint32_t)off_wpal_bg);
    put_u24(hdr + 20, (uint32_t)off_wpal_spr);

    if (buf_append(blob, hdr, WORLD_HDR_SIZE) != 0) {
        return -1;
    }

    for (bi = 0; bi < R01_BG_BANKS; bi++) {
        uint8_t bank[R01_CHR_BANK_BYTES];
        size_t n;
        memset(bank, 0, sizeof(bank));
        n = (size_t)w->bg_banks[bi].tile_count * R01_TILE_BYTES;
        if (n > sizeof(bank)) {
            n = sizeof(bank);
        }
        memcpy(bank, w->bg_banks[bi].chr, n);
        if (buf_append(blob, bank, sizeof(bank)) != 0) {
            return -1;
        }
    }
    for (bi = 0; bi < R01_SPR_BANKS; bi++) {
        uint8_t bank[R01_CHR_BANK_BYTES];
        size_t n;
        memset(bank, 0, sizeof(bank));
        n = (size_t)w->spr_banks[bi].tile_count * R01_TILE_BYTES;
        if (n > sizeof(bank)) {
            n = sizeof(bank);
        }
        memcpy(bank, w->spr_banks[bi].chr, n);
        if (buf_append(blob, bank, sizeof(bank)) != 0) {
            return -1;
        }
    }

    if (w->use_world_pals) {
        if (append_pal_rows(blob, w->pal_bg) != 0 || append_pal_rows(blob, w->pal_spr) != 0) {
            return -1;
        }
    }

    for (si = 0; si < w->screen_count; si++) {
        const R01Screen *s = &w->screens[si];
        uint8_t *e = dir + (size_t)si * SCREEN_DIR_ENT;
        uint32_t poff = payload_base + (uint32_t)si * SCREEN_PAYLOAD;
        put_u8(e + 0, (uint8_t)s->col);
        put_u8(e + 1, (uint8_t)s->row);
        put_u8(e + 2, (uint8_t)((w->default_bg_bank & 3) | ((w->default_pal_row & 3) << 2)));
        put_u8(e + 3, 0);
        put_u24(e + 4, poff);
        put_u24(e + 7, 0);
    }
    if (w->screen_count > 0 &&
        buf_append(blob, dir, (size_t)w->screen_count * SCREEN_DIR_ENT) != 0) {
        return -1;
    }

    {
        int written = 0;
        uint32_t plane_payload = payload_base + (uint32_t)w->screen_count * SCREEN_PAYLOAD;
        for (pi = 0; pi < R01_MAX_PARALLAX_PLANES; pi++) {
            const R01ParallaxPlane *pl = &w->planes[pi];
            uint8_t *e;
            if (!pl->present) {
                continue;
            }
            e = pdir + (size_t)written * PLANE_DIR_ENT;
            put_u8(e + 0, (uint8_t)(pl->slot & 1));
            put_u8(e + 1, 0);
            put_u8(e + 2, 0);
            put_u8(e + 3, 0);
            put_u24(e + 4, plane_payload + (uint32_t)written * SCREEN_PAYLOAD);
            written++;
        }
        if (written > 0 && buf_append(blob, pdir, (size_t)written * PLANE_DIR_ENT) != 0) {
            return -1;
        }
    }

    for (si = 0; si < w->screen_count; si++) {
        const R01Screen *s = &w->screens[si];
        if (buf_append(blob, s->tiles, R01_TILES_PER_SCREEN) != 0 ||
            buf_append(blob, s->attrs, R01_ATTRS_PER_SCREEN) != 0) {
            return -1;
        }
    }
    for (pi = 0; pi < R01_MAX_PARALLAX_PLANES; pi++) {
        const R01ParallaxPlane *pl = &w->planes[pi];
        if (!pl->present) {
            continue;
        }
        if (buf_append(blob, pl->tiles, R01_TILES_PER_SCREEN) != 0 ||
            buf_append(blob, pl->attrs, R01_ATTRS_PER_SCREEN) != 0) {
            return -1;
        }
    }
    return 0;
}

int r01_cart_build(const R01Project *p, uint8_t **out, size_t *out_len, char *err_buf, size_t err_cap) {
    Buf cart = {0};
    R01Project *work = NULL;
    uint8_t hdr[HDR_SIZE];
    uint8_t ptrs[PTR_TABLE_SIZE];
    uint8_t wtable[WORLD_TABLE_SIZE];
    uint8_t prg[R01_PRG_BYTES];
    uint32_t off_prg, off_pal_bg, off_pal_spr, off_wtable;
    int wi, world_count = 0;
    Buf world_blobs[R01_MAX_WORLDS];

    if (!p || !out || !out_len) {
        set_err(err_buf, err_cap, "bad args");
        return -1;
    }
    *out = NULL;
    *out_len = 0;
    memset(world_blobs, 0, sizeof(world_blobs));

    work = (R01Project *)malloc(sizeof(R01Project));
    if (!work) {
        set_err(err_buf, err_cap, "oom");
        return -1;
    }
    memcpy(work, p, sizeof(R01Project));

    for (wi = 0; wi < R01_MAX_WORLDS; wi++) {
        if (work->worlds[wi].present) {
            prepare_world_chr(&work->worlds[wi]);
            world_count++;
        }
    }
    if (world_count < 1) {
        free(work);
        set_err(err_buf, err_cap, "no worlds");
        return -1;
    }

    memset(hdr, 0, sizeof(hdr));
    memcpy(hdr, "RETR01", 6);
    hdr[6] = R01_CART_FORMAT_VER;
    hdr[7] = (uint8_t)world_count;
    hdr[8] = (uint8_t)(work->has_cart_save ? R01_CART_FLAG_I2C_SAVE : 0);

    r01_prg_fill_stub(prg, work);

    for (wi = 0; wi < R01_MAX_WORLDS; wi++) {
        if (!work->worlds[wi].present) {
            continue;
        }
        if (build_world_blob(&world_blobs[wi], &work->worlds[wi]) != 0) {
            goto oom;
        }
    }

    off_pal_bg = HDR_SIZE + PTR_TABLE_SIZE;
    off_pal_spr = off_pal_bg + 16;
    off_prg = off_pal_spr + 16;
    off_wtable = off_prg + R01_PRG_BYTES;

    memset(ptrs, 0, sizeof(ptrs));
    put_u24(ptrs + 0, off_prg);
    put_u24(ptrs + 3, R01_PRG_BYTES);
    put_u24(ptrs + 6, off_pal_bg);
    put_u24(ptrs + 9, 16);
    put_u24(ptrs + 12, off_pal_spr);
    put_u24(ptrs + 15, 16);
    put_u24(ptrs + 18, off_wtable);
    put_u24(ptrs + 21, WORLD_TABLE_SIZE);

    if (buf_append(&cart, hdr, HDR_SIZE) != 0 || buf_append(&cart, ptrs, PTR_TABLE_SIZE) != 0 ||
        append_pal_rows(&cart, work->global_pal_bg) != 0 ||
        append_pal_rows(&cart, work->global_pal_spr) != 0 || buf_append(&cart, prg, R01_PRG_BYTES) != 0) {
        goto oom;
    }

    {
        uint32_t cursor = off_wtable + WORLD_TABLE_SIZE;
        memset(wtable, 0, sizeof(wtable));
        for (wi = 0; wi < R01_MAX_WORLDS; wi++) {
            uint8_t *slot = wtable + (size_t)wi * WORLD_SLOT_SIZE;
            if (!work->worlds[wi].present) {
                continue;
            }
            put_u8(slot + 0, 1);
            put_u8(slot + 1, 0);
            put_u24(slot + 2, cursor);
            put_u24(slot + 5, (uint32_t)world_blobs[wi].len);
            cursor += (uint32_t)world_blobs[wi].len;
        }
    }

    if (buf_append(&cart, wtable, WORLD_TABLE_SIZE) != 0) {
        goto oom;
    }
    for (wi = 0; wi < R01_MAX_WORLDS; wi++) {
        if (!work->worlds[wi].present) {
            continue;
        }
        if (buf_append(&cart, world_blobs[wi].data, world_blobs[wi].len) != 0) {
            goto oom;
        }
    }

    for (wi = 0; wi < R01_MAX_WORLDS; wi++) {
        free(world_blobs[wi].data);
    }
    free(work);
    *out = cart.data;
    *out_len = cart.len;
    return 0;

oom:
    for (wi = 0; wi < R01_MAX_WORLDS; wi++) {
        free(world_blobs[wi].data);
    }
    free(cart.data);
    free(work);
    set_err(err_buf, err_cap, "oom");
    return -1;
}

int r01_cart_write(const R01Project *p, const char *path, char *err_buf, size_t err_cap) {
    uint8_t *img = NULL;
    size_t len = 0;
    FILE *f;
    if (r01_cart_build(p, &img, &len, err_buf, err_cap) != 0) {
        return -1;
    }
    f = fopen(path, "wb");
    if (!f) {
        free(img);
        set_err(err_buf, err_cap, "cannot write cart");
        return -1;
    }
    if (fwrite(img, 1, len, f) != len) {
        fclose(f);
        free(img);
        set_err(err_buf, err_cap, "cart write failed");
        return -1;
    }
    fclose(f);
    free(img);
    return 0;
}

int r01_cart_write_flash(const R01Project *p, const char *path, char *err_buf, size_t err_cap) {
    uint8_t *img = NULL;
    size_t len = 0;
    Buf flash = {0};
    FILE *f;
    if (r01_cart_build(p, &img, &len, err_buf, err_cap) != 0) {
        return -1;
    }
    if (len > R01_CART_FLASH_BYTES) {
        free(img);
        set_err(err_buf, err_cap, "cart too large for 512KB");
        return -1;
    }
    if (buf_append(&flash, img, len) != 0 || buf_pad(&flash, R01_CART_FLASH_BYTES, 0xFF) != 0) {
        free(img);
        free(flash.data);
        set_err(err_buf, err_cap, "oom");
        return -1;
    }
    free(img);
    f = fopen(path, "wb");
    if (!f) {
        free(flash.data);
        set_err(err_buf, err_cap, "cannot write flash");
        return -1;
    }
    if (fwrite(flash.data, 1, flash.len, f) != flash.len) {
        fclose(f);
        free(flash.data);
        set_err(err_buf, err_cap, "flash write failed");
        return -1;
    }
    fclose(f);
    free(flash.data);
    return 0;
}

int r01_export_bundle(const R01Project *p, const char *path_stem, char *err_buf, size_t err_cap) {
    char path[R01_PATH_MAX];
    if (!p || !path_stem) {
        set_err(err_buf, err_cap, "bad args");
        return -1;
    }
    snprintf(path, sizeof(path), "%s.retr01", path_stem);
    if (r01_cart_write(p, path, err_buf, err_cap) != 0) {
        return -1;
    }
    snprintf(path, sizeof(path), "%s_prom.bin", path_stem);
    if (r01_prom_write(path, err_buf, err_cap) != 0) {
        return -1;
    }
    snprintf(path, sizeof(path), "%s_boot.s", path_stem);
    if (r01_prg_write_asm(p, path, err_buf, err_cap) != 0) {
        return -1;
    }
    snprintf(path, sizeof(path), "%s_flash.bin", path_stem);
    if (r01_cart_write_flash(p, path, err_buf, err_cap) != 0) {
        return -1;
    }
    return 0;
}

int r01_cart_peek_header(const uint8_t *img, size_t len, int *world_count, uint32_t *prg_off,
                         uint32_t *prg_len) {
    if (!img || len < HDR_SIZE + PTR_TABLE_SIZE) {
        return -1;
    }
    if (memcmp(img, "RETR01", 6) != 0) {
        return -1;
    }
    if (world_count) {
        *world_count = img[7];
    }
    if (prg_off) {
        *prg_off = get_u24(img + HDR_SIZE + 0);
    }
    if (prg_len) {
        *prg_len = get_u24(img + HDR_SIZE + 3);
    }
    return 0;
}
