#!/usr/bin/env python3
"""Generate Retr01 global system palette docs and tool palettes from apps/common/r01_kit_palette.c."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SRC = REPO_ROOT / "apps" / "common" / "r01_kit_palette.c"
OUT_DIR = Path(__file__).resolve().parent
BEGIN = "R01_KIT_RGB_BEGIN"
END = "R01_KIT_RGB_END"
HEX_TRIPLE = re.compile(
    r"\{\s*0x([0-9A-Fa-f]{2})\s*,\s*0x([0-9A-Fa-f]{2})\s*,\s*0x([0-9A-Fa-f]{2})\s*\}"
)


def parse_kit_rgb(src_text: str) -> list[tuple[int, int, int]]:
    begin = src_text.find(BEGIN)
    end = src_text.find(END)
    if begin < 0 or end < 0 or end <= begin:
        raise ValueError(f"missing {BEGIN} / {END} markers in kit source")
    block = src_text[begin:end]
    colors = [(int(m.group(1), 16), int(m.group(2), 16), int(m.group(3), 16)) for m in HEX_TRIPLE.finditer(block)]
    if len(colors) != 64:
        raise ValueError(f"expected 64 kit colors, found {len(colors)}")
    return colors


def write_md(path: Path, colors: list[tuple[int, int, int]]) -> None:
    lines = [
        "# Global system palette",
        "",
        "Locked motherboard **64-color** kit (AT27C256R indices **0..63**).",
        "",
        "Source of truth: [`apps/common/r01_kit_palette.c`](../../apps/common/r01_kit_palette.c).",
        "Studio and Emu link that table for preview RGB. Cart palette planes store kit indices only.",
        "PROM burn packs each entry as **R3G3B2** (`{RRRGGGBB}`).",
        "",
        "This file is generated by `gen_kit_palette.py`. Do not edit by hand.",
        "",
        "Bands: **0..15** darkest, **16..31** mid-dark, **32..47** mid, **48..63** bright.",
        "",
        "| Index | R | G | B | Hex |",
        "|------:|--:|--:|--:|------|",
    ]
    for i, (r, g, b) in enumerate(colors):
        lines.append(f"| {i} | {r} | {g} | {b} | `{r:02X}{g:02X}{b:02X}` |")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_gpl(path: Path, colors: list[tuple[int, int, int]]) -> None:
    lines = [
        "GIMP Palette",
        "Name: Retr01 Global System",
        "Columns: 16",
        "# Generated from apps/common/r01_kit_palette.c by gen_kit_palette.py",
    ]
    for i, (r, g, b) in enumerate(colors):
        lines.append(f"{r:3d} {g:3d} {b:3d} Index {i}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_jasc_pal(path: Path, colors: list[tuple[int, int, int]]) -> None:
    # JASC-PAL: Aseprite Load Palette (.pal)
    lines = ["JASC-PAL", "0100", str(len(colors))]
    for r, g, b in colors:
        lines.append(f"{r} {g} {b}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--src",
        type=Path,
        default=DEFAULT_SRC,
        help="path to r01_kit_palette.c (default: apps/common/r01_kit_palette.c)",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=OUT_DIR,
        help="output directory (default: this script's directory)",
    )
    args = ap.parse_args()
    src = args.src.resolve()
    out_dir = args.out_dir.resolve()
    if not src.is_file():
        print(f"error: kit source not found: {src}", file=sys.stderr)
        return 1
    colors = parse_kit_rgb(src.read_text(encoding="utf-8"))
    out_dir.mkdir(parents=True, exist_ok=True)
    write_md(out_dir / "global_system_palette.md", colors)
    write_gpl(out_dir / "retr01_global_system.gpl", colors)
    write_jasc_pal(out_dir / "retr01_global_system.pal", colors)
    print(f"wrote {len(colors)} colors into {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
