#!/usr/bin/env bash
# Remove generated byproducts that landed in the repo root.
# Canonical outputs live under apps/sim/*/ or apps/sim/tier-h/skidl/.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT" || exit 0

rm -f \
  retr01_tier_h.json \
  retr01_prelim.net \
  skidl.erc \
  skidl.log \
  __init__.erc \
  __init__.log \
  skidl_from_tier_h_sklib.py \
  ui_layout.json \
  test_layout.json \
  test_cart.retr01 \
  test_cart_pb.retr01 \
  test_prom.bin \
  listing.txt \
  sdk_overlay.prg \
  sdk_overlay.prg.elf \
  test_roundtrip.r01proj \
  bad_fmt1.retr01 \
  test_bgm_v14.r01proj \
  test_bgm_ins.r01proj \
  test_ase_import.r01proj \
  fixture_export.retr01

rm -f skidl_from_tier_h.* skidl_REPL.*
exit 0
