name: unit-tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc pkg-config libsdl2-dev libpng-dev libfreetype6-dev
      - name: Install llvm-mos
        run: ./scripts/fetch-llvm-mos.sh
      - name: Run unit tests
        run: ./scripts/unit-tests.sh
